# Generated by Django 5.2.6 on 2025-09-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_order_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('first', 'Первые блюда'), ('second', 'Вторые блюда'), ('garnish', 'Гарнир')], default='second', max_length=50, verbose_name='Категория'),
        ),
    ]
