# Generated by Django 5.2.6 on 2025-10-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='floor',
            field=models.CharField(blank=True, max_length=10, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='order',
            name='room',
            field=models.CharField(blank=True, max_length=20, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
