# Generated by Django 5.2.6 on 2025-10-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_order_floor_order_room_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес доставки'),
        ),
    ]
